### ISSUE TITLE
QgisInterface.legendInterface() should return the right object

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#177]
The `legendInterface` method of QgisInterface mock in `svir/test/qgis_interface.py` returns the canvas instead of the legend, breaking things like `IFACE.legendInterface().refreshLayerSymbology()`. I made a workaround in https://github.com/gem/oq-irmt-qgis/blob/master/svir/test/utilities.py#L67, but it does not look so good to me.

Another problem of QgisInterface mock is that it is impossible to set and get the active layer.

**Comment by ptormene** [comment]
Instead of the ugly workaround, that removes all the layers except the one I am analyzing, a cleaner solution would be to retrieve layers by name.

**Comment by mbernasocchi** [comment]
these problems are adressed in branch fix-177
