### ISSUE TITLE
Help file not found

### ISSUE THREAD

**Issue by ismailsunni** [gem/oq-irmt-qgis#196]
After installing it on QGIS 2.14.10 on OSX, I tried to click the `Plugin's Manual` button. But I got an error message:
```
Error: Help file not found:
/Users/ismailsunni/.qgis2/python/plugins/svir/help/build/html/index.html
```

**Comment by ptormene** [comment]
Starting from the "stable" version v1.8.25, the plugin's manual can be loaded correctly
