### ISSUE TITLE
When hovering on curves, points on map are not highlighted if a open layer is loaded

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#204]
I suspect it is due to some kind of conflict with the management of signals.
It happens, for instance, after you load OpenLayers->OpenStreetMap->OpenStreetMap. Even after removing OpenStreetMap, the problem still persists.

**Comment by mbernasocchi** [comment]
on 2.18+ there is no need for open layers btw. see http://gis.stackexchange.com/questions/20191/adding-basemaps-from-google-or-bing-in-qgis/217670#217670

**Comment by ptormene** [comment]
Thank you @mbernasocchi! I've tried adding OpenStreetMap the way you suggested, and the highlighting works perfectly. I will add a note to the manual, to describe this.

**Comment by mbernasocchi** [comment]
great, the less plugins we depend on the better

**Comment by mbernasocchi** [comment]
and OL plugin was never one of my favourites
