### ISSUE TITLE
IMT selector in GMF outputs returns an error when calc has only one event

### ISSUE THREAD

**Issue by daniviga** [gem/oq-irmt-qgis#226]
![screenshot from 2017-05-09 17-07-00](https://cloud.githubusercontent.com/assets/1818657/25857630/f424aed2-34d9-11e7-84f3-6c98c0fd5adf.png)

```
IndexError: tuple index out of range 
Traceback (most recent call last):
  File "/home/daniele/.qgis2/python/plugins/svir/dialogs/load_gmf_data_as_layer_dialog.py", line 72, in on_imt_changed
    max_eid = (self.dataset[imt].shape[1] - 1)
IndexError: tuple index out of range
```

The error is raised because we assume always more than one Event ID. A demo calculation provided by @CatalinaYepes instead had just one Event.

**Comment by ptormene** [comment]
Fixed engine-side: https://github.com/gem/oq-engine/pull/2785
