### ISSUE TITLE
Error message when downloading csv files with QGIS plugin

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-irmt-qgis#250]
When downloading OQ outputs in csv, the plugin shows the following error message, but it download the files.
![screen shot 2017-05-24 at 18 14 16](https://cloud.githubusercontent.com/assets/6975363/26413683/05640baa-40ad-11e7-9f71-6c6d440538f9.png)

**Comment by daniviga** [comment]
I'm not able to reproduce the issue running Fedora 25, QGIS 2.18.8, SVIR 1.8.25 and oq-engine from master (fe4a4bc).

Can you try to manually remove the plugin (rm -Rf ~/.qgis2/python/plugins/svir) and re-install it? Maybe you have a pyc cached.

**Comment by daniviga** [comment]
We should check if it's possible to cleanup pyc during and upgrade
