### ISSUE TITLE
Plugin is complaining about colors (macOS)

### ISSUE THREAD

**Issue by daniviga** [gem/oq-irmt-qgis#251]
Loading an hmap from the ClassicalRisk demo the plugin complaints about 'colors':

![screen shot 2017-05-26 at 11 12 33](https://cloud.githubusercontent.com/assets/1818657/26488763/02f5208a-4205-11e7-8c26-5cd33b6b24a9.png)

This also happens with other demos.

QGIS 2.18.7 (from KingChaos), SVIR 1.8.25, Engine 2.4.0, macOS Sierra

**Comment by daniviga** [comment]
I was unable to reproduce the issue on Linux (QGIS 2.18.7, Engine 2.4.0, Fedora 25)

**Comment by ptormene** [comment]
Ciao. Il problema dei colori forse dovrebbe essere di tipo info invece che
error. Si tratta di un problema di migrazione da una versione vecchia.
Prima il dato era salvato in un diverso formato. Quando il plugin se ne
accorge, migra il dato. Da quel momento in poi, non dovrebbe più dare
nessun problema. L'errore dovrebbe comparire solo una volta, quando viene
mirato il dato. Se dovesse succedere di nuovo per lo stesso utente sulla
stessa macchina, significa che abbiamo un bug. Se no, è il comportamento
giusto. Il fatto che sia error e non info è perché il plugin ripristina i
default, quindi è giusto che ti avvisi in modo più visibile.

Ciao,
Paolo

Il 26 Mag 2017 11:21, "Daniele Viganò" <notifications@github.com> ha
scritto:

**Comment by micheles** [comment]
Non c'e' anche il livello warning?

2017-05-26 11:44 GMT+02:00 Paolo Tormene <notifications@github.com>:
