### ISSUE TITLE
Hazard curves plot is missing the investigation time

### ISSUE THREAD

**Issue by daniviga** [gem/oq-irmt-qgis#288]
Talking with @mmpagani about the web visualization of the hazard curves he was pointing out the fact that the hazard curves chart is missing the investigation time, which is important for the completeness of the information.

I don't know if this information is exported in the hazard map or in any other type of output (apart from the fullreport).

**Comment by ptormene** [comment]
When we download hazard curves, the plugin could also call the engine server to load the calculation parameters and get the investigation time. Then it could associate the investigation time to the layer as a custom property. When the Data Viewer finds the investigation time associated to the layer, it can display it in the title of the plot.

**Comment by micheles** [comment]
Notice also https://github.com/gem/oq-engine/issues/2568

**Comment by ptormene** [comment]
Having the investigation time inside the npz for hcurves would simplify a lot the plugin side logic. It would be especially important in the use case in which one wants to load an npz directly, without passing from the dialog that drives the oq-engine. In that case, you could not call the oq-engine to retrieve the investigation time. Once you have the information, while building the qgis layer, it still sounds reasonable to save the investigation time as a custom property of the layer, that will be saved in the qgis project.
