### ISSUE TITLE
Append to the exported filenames the id of the OQ-Engine calculation

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#320]
Some outputs are managed dynamically using the new "extract" api. For those, it's trivial to keep track of the calculation id. For the old outputs that are loaded as layers from npz, it is a bit more complicated. We should save the calculation id somewhere, e.g., as a key in the npz, or in the layer name. The latter sounds less robust, because the user might want to modify the layer name afterwards, possibly breaking things. We are already saving the investigation time, and contextually we could save also the calculation id (it should be done engine-side). As soon as the calculation id becomes available in the npz, I can save it as a property of the layer using setCustomProperty, and therefore I can get it when the layer is switched and visualized in the Data Viewer dock. Until then, I prefer to block this issue.

**Comment by ptormene** [comment]
We are probably going to discard the "download npz" approach, using the "extract api" instead, for all outputs. Therefore, this problem will disappear. Until then, perhaps it's not worth the effort of adding the calc id engine-side. @micheles, what's your opinion on this?

**Comment by micheles** [comment]
Paolo, notice that an user downloading the .npz from the WebUI gets the calc_id at the end of the filename (just tried with the hazard curves of https://oq2.wilson.openquake.org/engine/17583/outputs). So I do not understand what the problem is.

**Comment by ptormene** [comment]
Thanks, I hadn't noticed it. Then it should be easy.

**Comment by ptormene** [comment]
With the change introduced by https://github.com/gem/oq-irmt-qgis/pull/393, all the files exported by the Data Viewer contain the calculation id. Still, there are some npz files that are visualized as maps and that do not have a corresponding "export" functionality. So, things should be fine now.
