### ISSUE TITLE
We want to be able to aggregate the avg_losses-stats from the QGIS plugin

### ISSUE THREAD

**Issue by micheles** [gem/oq-irmt-qgis#395]
Currently we are only aggregating the losses for scenario_risk and scenario_damage.

**Comment by ptormene** [comment]
It should be very similar to loading Average Asset Losses (2 buttons: "Load layer" and "Aggregate")

**Comment by ptormene** [comment]
Fixed in https://github.com/gem/oq-irmt-qgis/pull/425
