### ISSUE TITLE
Use the extract api to load engine outputs as layers

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#401]
We are still using the previous approach (downloading a NPZ) for:

- [x] dmg_by_asset
- [x] losses_by_asset
- [x] gmf_data

We are still loading from CSV for:

- [x] ruptures
- [ ] basic csv files loaded as they are (realizations, events, dmg_by_event, losses_by_event, agglosses, agg_risk)

**Comment by micheles** [comment]
The ruptures are not obvious to extract, let's keep them as they are for the moment.
