### ISSUE TITLE
Tests are skipped for `losses_by_asset_aggr` and `dmg_by_asset_aggr`

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#402]
On Ubuntu 16.04 things work fine, but those tests break on Travis and we must check what happens on 

- [x] Windows: OK
- [x] Mac: OK
- [ ] Ubuntu 14.04: KO
- [X] Ubuntu 16.04: OK
- [X] Fedora: OK

**Comment by daniviga** [comment]
This Docker file can be used to build a development environment to test these issues:

[Dockerfile.txt](https://github.com/gem/oq-irmt-qgis/files/1797177/Dockerfile.txt)

**Comment by daniviga** [comment]
It looks working fine on Windows (QGIS-OSGeo4W-2.18.17-1-Setup-x86.exe)

**Comment by daniviga** [comment]
Works on macOS too (using Kyngchaos)
