### ISSUE TITLE
Option to visualize csv outputs with the plugin

### ISSUE THREAD

**Issue by CatalinaYepes** [gem/oq-irmt-qgis#413]
Option to visualize from the plugin the output files that are in csv. Currently users have to download them to see the content.

- `realizations`
- `Seismic Source Groups`
- ` Aggregate Loss Table` (in event-based calculations)

**Comment by ptormene** [comment]
@micheles pointed out that the CSV files might contain millions of lines, so we should at least set up some limits and prevent users from attempting to load files that are too big.

**Comment by CatalinaYepes** [comment]
I agree. This is only the case for `Aggregate Loss Table` outputs. We can do as in excel, when for big files, they tell you that only a sample of the data will be displayed (maybe the first n lines).

**Comment by daniviga** [comment]
Why we don't simply download these files, save them locally and open them with the default system program (like Excel or LibreOffice) as the pure WebUI does? I would not try to reinvent the wheel (resize of columns, filters, ordering, memory allocation etc...) when we can rely on specialized software.

**Comment by ptormene** [comment]
The idea is to do exactly what we do with ruptures: loading the csv directly, using the QGIS importer, and saving it as a layer. Ruptures have also coordinates, so they can be visualized in a map. Other outputs that do not have coordinates, can be visualized in their attribute tables. QGIS natively provides features like sorting by field, filtering, and so forth. So we are not reimplementing anything complex.

**Comment by ptormene** [comment]
For now, we must postpone loading aggregate loss tables. See https://github.com/gem/oq-engine/issues/3445
