### ISSUE TITLE
Style ruptures automatically

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#435]
Usually, there are 2 alternative ways to style ruptures:

1. by trt
2. by mag

Scientists should decide if they want ruptures to be styled automatically and, in case they do, which styling should we apply automatically by default (unless we want to give the user a choice through a dropdown menu).

**Comment by CatalinaYepes** [comment]
It will be better to style the ruptures by TRT. You can give random colors (generally, there are not many categories).
