### ISSUE TITLE
Allow hazard curves to be filtered by PoE and/or IMT

### ISSUE THREAD

**Issue by daniviga** [gem/oq-irmt-qgis#485]
When downloading an hazard curves layer all the exported data is loaded.

In the case of the hazard map for Colombia this means (13 IMTs * 6 PoEs * 9676 sites) for a total of almost 1.6k columns and 15M values which makes the layer unusable.

In the specific case only 5 PoEs and 3 IMTs are needed, so it would be good to add a filtering option before rendering the layer. A multiple selection (i.e. multiple IMTs) would be the best.

A similar (just for PoEs) is used by UHS.

**Comment by ptormene** [comment]
In hcurves, we might filter by rlz, imt and iml, but curves make no sense if you don't load values for all intensity measure levels. Therefore, what we can do is adding filters for realization/statistic and for imts.
