### ISSUE TITLE
Button to show sidebar could have an inverted status

### ISSUE THREAD

**Issue by daniviga** [gem/oq-irmt-qgis#514]
I would expect the button to looks 'clicked' when sidebar is open and not the opposite

![sidebar_open](https://user-images.githubusercontent.com/1818657/46211394-b9a2c200-c333-11e8-9136-310b62257170.jpg)

![sidebar_closed](https://user-images.githubusercontent.com/1818657/46211395-bb6c8580-c333-11e8-9ae8-49b2395ba953.jpg)

I guess that status is only a flip-flop and is not taking into account changes made via QGIS toolbar menu.

**Comment by daniviga** [comment]
> I guess that status is only a flip-flop and is not taking into account changes made via QGIS toolbar menu

Button is unclicked when sidebar is hidden via menu, but it is not 'clicked' when sidebar is activated via menu, causing the sidebar and button to go out of sync.

![peek 2018-09-28 15-35](https://user-images.githubusercontent.com/1818657/46211650-63824e80-c334-11e8-903a-221116f9d462.gif)

**Comment by ptormene** [comment]
The very strange thing is that on my laptop the behavior of the button is exactly as expected. But I've seen the issue happening sometimes in the past. I have to understand what might cause it.

**Comment by ptormene** [comment]
Actually, on my laptop, toggling works, but the status might be inverted if the Data Viewer is disabled when the plugin is loaded.
