### ISSUE TITLE
Replace QtWebKit with QtWebEngine

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#516]
On ubuntu, it requres
```bash
$ sudo apt install python3-pyqt5.qtwebengine
```

**Comment by ptormene** [comment]
It seems to be blocked by what's described here: https://issues.qgis.org/issues/18155

**Comment by mbernasocchi** [comment]
nobody likes QtWebEngine :)

**Comment by mbernasocchi** [comment]
have a look at this therad: https://lists.osgeo.org/pipermail/qgis-developer/2018-September/054537.html

**Comment by ptormene** [comment]
We are not using this kind of feature anymore
