### ISSUE TITLE
Matplotlib 3.0.0 can't import pyplot on Mac OS

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#519]
It was impossible to install the plugin on a brand new mac with a fresh installation of matplotlib. We found out that the problem can be fixed downgrading matplotlib to version 2.2.2

**Comment by daniviga** [comment]
Why this is has been assigned to me?
I guess the only solution is or to force users to have matplotlib < 3.0 or to change the plugins to be compatible with the new matplotlib.

**Comment by ptormene** [comment]
@daniviga I've assigned it to you, just to let you know about the problem, in case anybody asks for your support on installation. Probably the best we can do now is updating the installation instructions of the plugin, specifying that matplotlib v2.2.2 should be installed on mac, until that bug is fixed on matplotlib v3

**Comment by daniviga** [comment]
Matplotlib 3.0.0 works fine with QGIS 3.2.3 on Fedora:

![screenshot from 2018-10-08 08-40-17](https://user-images.githubusercontent.com/1818657/46594884-eabe8780-cad5-11e8-9e55-fc5c4037c76f.png)

To test it against newer python dependencies without braking the system you have to:

```bash
$ python3 -m venv --system-site-packages mpl3
$ source mpl3/bin/activate
$ pip install -U matplotlib
$ qgis
```

**Comment by daniviga** [comment]
@ptormene the issue looks to be related on to macOS and is caused by:
https://github.com/matplotlib/matplotlib/issues/12291

**Comment by ptormene** [comment]
Instructions on how to work around this issue have been released: https://github.com/gem/oq-irmt-qgis/pull/520
