### ISSUE TITLE
Show the message log automatically whenever an error occurs

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#539]
From the QGIS-Developer mailing list, the way to do it would be:
```python
for widget in iface.mainWindow().children():
    if widget.objectName() == 'MessageLog':
        widget.show()
```
Or shorter (but trickier):
```python
iface.mainWindow().findChild(QDockWidget, 'MessageLog').show()
```

**Comment by ptormene** [comment]
@mbernasocchi, this sounded quick and easy, but I was unable to connect `QgsMessageLog::messageReceived` with a function that shows the dock widget with the logs. I found some examples online, but they were outdated and they did not work with the current version of QgsMessageLog.

**Comment by ptormene** [comment]
@mbernasocchi, discussing at scrum about this, we arrived to the conclusion that this kind of thing should not be managed by the plugin, but it should be a functionality offered by the QgsMessageLog class. I've just noticed that QgsMessageLog.logMessage has the parameter `notifyUser` that is `True` by default. But it doesn't seem to do what I would like.

Example:
in the QGIS Python Console, while the log dock widget is not shown, type:
```python
QgsMessageLog.logMessage("message", "tab name", Qgis.Critical, True)
```
It logs the message in the correct tab, but completely silently. I can see the message only if I press the button to open the log dock widget.

**Comment by mbernasocchi** [comment]
the best way to communicate to the user is by using the messagebar, you can add there the following code to popup the log
`iface.mainWindow().findChildren(QToolButton, 'mMessageLogViewerButton')[0].setChecked(True)`

**Comment by mbernasocchi** [comment]
To select your tab you can do
```
dock = iface.mainWindow().findChild(QDockWidget, 'MessageLog')
tabs = dock.findChild(QTabWidget, 'tabWidget')
for tab in range(tabs.count()):
    text = tabs.tabText(tab)
    print(text)
    if text == 'RandomIntegerSumTask':
        print('found')
        tabs.setCurrentIndex(tab)
        break
```

**Comment by ptormene** [comment]
After some work, I arrived to the conlusion that in my specific case I need something different. I am opening a PR, adding a button to the messageBar in case `log_msg` is called passing an exception to it, so that the user can press that button and visualize the full traceback.
