### ISSUE TITLE
Check exported csv files on Windows

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#561]
On @pslh machine, we noticed that a csv file exported from the Data Viewer contained unexpected newlines, that might be due to different newline characters used on windows. We need to make sure the exported files are readable correctly on all the main operating systems.

**Comment by daniviga** [comment]
How did you open the file? I would consider that a viewer bug, not an export bug. You are probaly exporting files correctly with a `\n\r`

**Comment by ptormene** [comment]
I don't remember exactly, but I think he tried opening the csv with Excel, and perhaps also with vim

**Comment by ptormene** [comment]
And if I remember correctly, the export was about loss curves

**Comment by ptormene** [comment]
https://stackoverflow.com/questions/9845681/does-python-csv-writer-always-use-dos-end-of-line-characters
Probably I should follow the guidelines proposed in the last answer

**Comment by micheles** [comment]
That StackOverflow answer is wrong. The default behavior, i.e. not specifying os.linesep which means ending with `\r\n` always, is the right way to ensure portability.

**Comment by ptormene** [comment]
I checked, and the issue seems to be in the heading lines that display some information about the file, whereas the rows with data seem to be ok, using \r \n as expected.
