### ISSUE TITLE
Cannot connect to the OQ engine server

### ISSUE THREAD

**Issue by paolofor** [gem/oq-irmt-qgis#727]
Hi,

Hi all, I am exploring OQ for my research on medieval seismicity and am trying to build a risk map for medieval Europe (yes, it sounds odd but this is what I am doing)

I completed my analysis simply combining exposure data (urban populations) with seismic hazard values (from SHARE hazard maps) but would like to do something more rigorous using OQ. I downloaded the OQ plugin in my QGIS 3.10 but cannot connect to the OP engine. There's clearly an issue with the host, I tried to insert different web URLs but with no success. 

Sorry for bothering but think this is my last resort....
Thanks for your help since now!

Paolo

**Comment by ptormene** [comment]
Dear Paolo,
are you sure the OQ Engine WebUI is up and running? Before attempting to
access it via the QGIS plugin, could you try connecting to it through your
browser?
Please be aware that the host that you set into the QGIS IRMT plugin
settings, if the engine is running locally in your computer, should be
http://localhost:8800 (without /engine)
Best regards,
Paolo

Il giorno gio 9 apr 2020 alle ore 19:20 paolofor <notifications@github.com>
ha scritto:

**Comment by paolofor** [comment]
Thank you very much Paolo, very helpful indeed....!

I launched the OQ Engine WebUI from the terminal (oq webui start) and connected to the effective WebUI. Copying and pasting the web URL http://127.0.0.1:8800/engine/ and using my login details, QGIS eventually connected to the OQ engine.
I also tried to use the OQ engine locally but could not work it out, maybe you need to indicate the path of the folder where the OW engine is installed? 

Anyway, now this problem it is fixed.... Now the difficult part comes... Hope I will be able to process my data then ;)

Thank you very much once again!
BW
Paolo
