### ISSUE TITLE
Displaying average asset losses stats, tags remain partially hidden

### ISSUE THREAD

**Issue by ptormene** [gem/oq-irmt-qgis#756]
![QGIS-Agg Average Asset Losses](https://user-images.githubusercontent.com/350930/107625194-3f510f00-6c5c-11eb-965b-59ca7a6d83f8.png)

**Comment by ptormene** [comment]
Using Stochastic Event-Based Demo (Nepal) I don't have that issue on my machine:
![Screenshot from 2021-02-11 14-00-38](https://user-images.githubusercontent.com/350930/107639955-e4c2ad80-6c71-11eb-97b0-78114704941d.png)
@CatalinaYepes, please, can you point me to the example that caused the issue in your screenshot?

**Comment by CatalinaYepes** [comment]
Here is the example:
[EventBasedRisk.zip](https://github.com/gem/oq-irmt-qgis/files/5966463/EventBasedRisk.zip)

**Comment by ptormene** [comment]
That example was broken. I am using this other one for testing:
[eb_risk.zip](https://github.com/gem/oq-irmt-qgis/files/5966868/eb_risk.zip)

**Comment by ptormene** [comment]
Also in this case it is working on my machine. I am going to investigate if it works fine on Windows too.
![Screenshot from 2021-02-11 17-41-18](https://user-images.githubusercontent.com/350930/107668017-7b05cc00-6c90-11eb-972d-969c17826dba.png)

**Comment by ptormene** [comment]
Also on Windows 10 it is working correctly. @CatalinaYepes, it seems to be a mac-related problem.

![VirtualBox_Windows 10_12_02_2021_15_11_38](https://user-images.githubusercontent.com/350930/107778844-db564580-6d44-11eb-9f96-f3faa26ae2c8.png)

**Comment by ptormene** [comment]
On a MacOS Mojave VM I see the problem:

![remmina_MacOS Devs_172 16 210 14_2021215-101922 038202](https://user-images.githubusercontent.com/350930/107934017-cca7a280-6f7f-11eb-920f-b2ece528715e.png)
