### ISSUE TITLE
OpenQuake Data Viewer Labels for Aggregate Losses display incorrectly

### ISSUE THREAD

**Issue by alejocaldeGEM** [gem/oq-irmt-qgis#810]
## Issue

In the same event_based_risk.zip from this [issue](https://github.com/gem/oq-irmt-qgis/issues/809#issue-1572277210), when the user uses the button `Aggregate` of the `Average Asset Losses` output, the OpenQuake Data Viewer displays the losses using labels that are not legible. See the following:

![error2](https://user-images.githubusercontent.com/43442706/216947576-c8261555-48f8-4233-8582-fb221e4ea082.png)

## Intended Behavior

Previously, the labels would be displayed correctly, letting the user know that the aggregate losses are per realization (in the case of a single event), or total in the case of an event-based calculation. See below:

![intended_behavior2](https://user-images.githubusercontent.com/43442706/216949102-019514dc-bb87-4495-b167-b41e5db24b6c.png)

**Comment by ptormene** [comment]
While in scenario calculations there is a 1-to-1 correspondence between realizations and gsims, in event-based things are a lot more complex. See https://docs.openquake.org/oq-engine/advanced/master/logic_trees.html?highlight=realizations#the-logic-tree-demo
We need to discuss what we want to visualize. @micheles and I propose to postpone this after the release.

**Comment by ptormene** [comment]
Fixed in https://github.com/gem/oq-irmt-qgis/pull/859
