### ISSUE TITLE
Issue handling event_based_damage outputs

### ISSUE THREAD

**Issue by alejocaldeGEM** [gem/oq-irmt-qgis#839]
## General issue
The attached .zip file contains an event_based_damage calculation (the job_ebdamage.ini) . The user is providing a set of fragility curves and a set of 5 consequence models: collapsed, displaced, injuries, fatalities and losses. As a result, the calculation outputs contain the average annual number of each of these 5 risk metrics. However, the plug-in is unable to handle the expected outputs appropiately, thus losing some fuctionality.

OpenQuake engine v3.16.6
Plug-in version v3.16.2
QGIS v3.22

### Aggregate Risk Curves output
With event_based_risk calculations, the plug-in correctly allows the user to visualize the aggregated loss curves for economic loss and fatalities in the OpenQuake Data Viewer panel. The plug-in allows the user to press the 'Show' button, and chose the Loss Type for the curve, and the style (Absolute or relative) (see IMG_1).  I have attached the event_based_risk calculation (see job_ebrisk.ini) for reference.

![IMG_1](https://github.com/gem/oq-irmt-qgis/assets/43442706/e78d9b1e-f8b7-49da-9cdc-1c765cbb80f8)

With an event_based_damage calculation, the plug-in should do the same, allowing the user to press the 'Show' button on the output, and chose the Loss Type (this time, including any of the 5 risk metrics). Instead, the 'Show' button is disappears from the calculation outputs (see IMG_2), effectively preventing the user to explore the aggregated loss curve for any of the risk metrics.

![IMG_2](https://github.com/gem/oq-irmt-qgis/assets/43442706/e21ac5c4-68bd-42ab-976f-bf26abe3834c)

Notice that this is not a problem, with the calculation itself. On IMG_3 I provide the agglosscurve for collapsed buildings, made from the outputs of the calculation. 

![IMG_3](https://github.com/gem/oq-irmt-qgis/assets/43442706/ae735918-1945-402c-94c8-dfe8a3437bf3)

### Aggregated Risk Distributions -> Aggregate
The calculation has 5 realizations requested by the user. By pressing the 'Aggregate' button, from the Aggregate Risk Distributions output, the user should be able to see the aggregate risk for any of the chosen realizations (average annual number of the 5 risk metrics). However, the plug-in displays the results for the first realization (see IMG_4). However, it is unable to display the result if the user changes the tags, or asks for the results of the other realizations, showing up the error seen in IMG_5.

![IMG_4](https://github.com/gem/oq-irmt-qgis/assets/43442706/91e93741-c3d1-4469-862b-9dc457fc5cdc)

![IMG_5](https://github.com/gem/oq-irmt-qgis/assets/43442706/a3af5ded-3a20-4292-8e5b-624f5c5c4d7e)

### Aggregate Risk Distributions -> Load Layer
The calculation has 5 realizations requested by the user. By pressing the 'Load Layer' button, from the Aggregate Risk Distributions output, the user should be able to make a map of the aggregate risk for any of the chosen realizations (average annual number of any risk metrics .e.g. collapsed buildings). However, the plug-in does not allow the user to chose any other realization than rlz-000 (see IMG_6). This could be by design, say, we may not want to let the user chose a realization if there are too many (e.g. 1000 realizations). But then the user should be given the choice of making a map for the mean results, or an appropiate warning.

![IMG_6](https://github.com/gem/oq-irmt-qgis/assets/43442706/edcd50ad-4d40-4b16-a9d5-1f5bf2c4ad2a)

[Uploading Event_Based_Damage.zip…]()

**Comment by ptormene** [comment]
[Event_Based_Risk.zip](https://github.com/gem/oq-irmt-qgis/files/12844321/Event_Based_Risk.zip)
