### ISSUE TITLE
Issues with latest QGIS 3.28 Firenze

### ISSUE THREAD

**Issue by alejocaldeGEM** [gem/oq-irmt-qgis#840]
## Issue

In the last workshop, all users with the QGIS 3.28 Firenze LTR version (the latest stable version) experienced problems loading PSHA results. The message shown below was the common one I found across machines, happening when loading hazard maps or hazard curves.  All machines running OpenQuake v3.16.6 and plug-in v3.16.1

![image](https://github.com/gem/oq-irmt-qgis/assets/43442706/e257c491-2ed8-4d96-8aa6-273a2eec096f)
![image](https://github.com/gem/oq-irmt-qgis/assets/43442706/6f8c3412-a23d-4497-8875-64fc1379f8b6)

Today I wanted to test this in my computer, so I updated the QGIS from 3.22 to 3.28, and pulled the latest from the plug-in 3.16.2. Using the attached PSHA calculation, QGIS crashes when asking for the hazard curves. @ptormene it is worth trying to replicate this issue on your side. Separately, I would also recommend trying to run the calculation on a Windows 11 machine, as this OS is becoming more and more popular.

**Comment by ptormene** [comment]
In the errors I spot some paths that look wrong, with some slashes and some backslashes inside the same path. I will try to replicate the error on linux and on a Windows VM.
